DKIM-Signature: v=1; a=ed25519-sha256; c=simple/simple; 
 d=football.example.com; i=@football.example.com; 
 q=dns/txt; s=brisbane; t=1518460054; h=from : to : 
 subject : date : message-id : from : subject : date; 
 bh=4bLNXImK9drULnmePzZNEBleUanJCX5PIsDIFoH4KTQ=; 
 b=9/dsDChY0YMTtD5Eyw3wx7x22BlSJP7M5ECbJ7GWrR45nXlTCGb8l0YB
 o0wBLR++X5LqmsxXaOYLLJe46l10AQ==
DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; 
 d=football.example.com; i=@football.example.com; 
 q=dns/txt; s=test; t=1527915362; h=from : to : subject : 
 date : message-id : from : subject : date; 
 bh=4bLNXImK9drULnmePzZNEBleUanJCX5PIsDIFoH4KTQ=; 
 b=icKcLSEZYXJ95flvWE8FT6hl5iqd8MC/LEKYH0QjsqYy6MO/4pgVNCZH
 l/RAXAuADxE/40Fg7uTlxwwD1hjN2Ple6J//cJfslBdDOq6zTVbne1dqtl
 NOat7iamJ1AfRqyG+ja7a2AZsrpUuJ7VA6O+0zRYPqpwMEkEFIzI9i/Xk=
From: Joe SixPack <joe@football.example.com>
To: Suzie Q <suzie@shopping.example.net>
Subject: Is dinner ready?
Date: Fri, 11 Jul 2003 21:00:37 -0700 (PDT)
Message-ID: <20030712040037.46341.5F8J@football.example.com>

Hi.

We lost the game.  Are you hungry yet?

Joe.

